apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "FancyName"
  description: "...sadsad"
  annotations:
    github.com/project-slug: outesting/FancyName
    backstage.io/techdocs-ref: dir:.
spec:
  type: repository
  lifecycle: experimental
  owner: "group:default/spiderman"
